export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';

export const ARCHIVE_EVENT_REQUEST = 'ARCHIVE_EVENT_REQUEST';
export const ARCHIVE_EVENT_SUCCESS = 'ARCHIVE_EVENT_SUCCESS';
export const ARCHIVE_EVENT_FAILURE = 'ARCHIVE_EVENT_FAILURE';

export const VALIDATE_EVENT_REQUEST = 'VALIDATE_EVENT_REQUEST';
export const VALIDATE_EVENT_SUCCESS = 'VALIDATE_EVENT_SUCCESS';
export const VALIDATE_EVENT_FAILURE = 'VALIDATE_EVENT_FAILURE';