export const FETCH_INFORMATIONS_REQUEST = 'FETCH_INFORMATIONS_REQUEST';
export const FETCH_INFORMATIONS_SUCCESS = 'FETCH_INFORMATIONS_SUCCESS';
export const FETCH_INFORMATIONS_FAILURE = 'FETCH_INFORMATIONS_FAILURE';

export const FETCH_INFORMATION_REQUEST = 'FETCH_INFORMATION_REQUEST';
export const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS';
export const FETCH_INFORMATION_FAILURE = 'FETCH_INFORMATION_FAILURE';

export const CREATE_INFORMATION_REQUEST = 'CREATE_INFORMATION_REQUEST';
export const CREATE_INFORMATION_SUCCESS = 'CREATE_INFORMATION_SUCCESS';
export const CREATE_INFORMATION_FAILURE = 'CREATE_INFORMATION_FAILURE';

export const UPDATE_INFORMATION_REQUEST = 'UPDATE_INFORMATION_REQUEST';
export const UPDATE_INFORMATION_SUCCESS = 'UPDATE_INFORMATION_SUCCESS';
export const UPDATE_INFORMATION_FAILURE = 'UPDATE_INFORMATION_FAILURE';

export const ARCHIVE_INFORMATION_REQUEST = 'ARCHIVE_INFORMATION_REQUEST';
export const ARCHIVE_INFORMATION_SUCCESS = 'ARCHIVE_INFORMATION_SUCCESS';
export const ARCHIVE_INFORMATION_FAILURE = 'ARCHIVE_INFORMATION_FAILURE';

export const VALIDATE_INFORMATION_REQUEST = 'VALIDATE_INFORMATION_REQUEST';
export const VALIDATE_INFORMATION_SUCCESS = 'VALIDATE_INFORMATION_SUCCESS';
export const VALIDATE_INFORMATION_FAILURE = 'VALIDATE_INFORMATION_FAILURE';
