export const RESOURCE_LIST_REQUEST = 'RESOURCE_LIST_REQUEST';
export const RESOURCE_LIST_SUCCESS = 'RESOURCE_LIST_SUCCESS';
export const RESOURCE_LIST_FAILURE = 'RESOURCE_LIST_FAILURE';

export const RESOURCE_DETAILS_REQUEST = 'RESOURCE_DETAILS_REQUEST';
export const RESOURCE_DETAILS_SUCCESS = 'RESOURCE_DETAILS_SUCCESS';
export const RESOURCE_DETAILS_FAILURE = 'RESOURCE_DETAILS_FAILURE';

export const RESOURCE_CREATE_REQUEST = 'RESOURCE_CREATE_REQUEST';
export const RESOURCE_CREATE_SUCCESS = 'RESOURCE_CREATE_SUCCESS';
export const RESOURCE_CREATE_FAILURE = 'RESOURCE_CREATE_FAILURE';

export const RESOURCE_UPDATE_REQUEST = 'RESOURCE_UPDATE_REQUEST';
export const RESOURCE_UPDATE_SUCCESS = 'RESOURCE_UPDATE_SUCCESS';
export const RESOURCE_UPDATE_FAILURE = 'RESOURCE_UPDATE_FAILURE';

export const RESOURCE_ARCHIVE_REQUEST = 'RESOURCE_ARCHIVE_REQUEST';
export const RESOURCE_ARCHIVE_SUCCESS = 'RESOURCE_ARCHIVE_SUCCESS';
export const RESOURCE_ARCHIVE_FAILURE = 'RESOURCE_ARCHIVE_FAILURE';

export const RESOURCE_VALIDATE_REQUEST = 'RESOURCE_VALIDATE_REQUEST';
export const RESOURCE_VALIDATE_SUCCESS = 'RESOURCE_VALIDATE_SUCCESS';
export const RESOURCE_VALIDATE_FAILURE = 'RESOURCE_VALIDATE_FAILURE';
