export const FETCH_TUTORIALS_REQUEST = 'FETCH_TUTORIALS_REQUEST';
export const FETCH_TUTORIALS_SUCCESS = 'FETCH_TUTORIALS_SUCCESS';
export const FETCH_TUTORIALS_FAILURE = 'FETCH_TUTORIALS_FAILURE';

export const FETCH_TUTORIAL_REQUEST = 'FETCH_TUTORIAL_REQUEST';
export const FETCH_TUTORIAL_SUCCESS = 'FETCH_TUTORIAL_SUCCESS';
export const FETCH_TUTORIAL_FAILURE = 'FETCH_TUTORIAL_FAILURE';

export const CREATE_TUTORIAL_REQUEST = 'CREATE_TUTORIAL_REQUEST';
export const CREATE_TUTORIAL_SUCCESS = 'CREATE_TUTORIAL_SUCCESS';
export const CREATE_TUTORIAL_FAILURE = 'CREATE_TUTORIAL_FAILURE';

export const UPDATE_TUTORIAL_REQUEST = 'UPDATE_TUTORIAL_REQUEST';
export const UPDATE_TUTORIAL_SUCCESS = 'UPDATE_TUTORIAL_SUCCESS';
export const UPDATE_TUTORIAL_FAILURE = 'UPDATE_TUTORIAL_FAILURE';

export const ARCHIVE_TUTORIAL_REQUEST = 'ARCHIVE_TUTORIAL_REQUEST';
export const ARCHIVE_TUTORIAL_SUCCESS = 'ARCHIVE_TUTORIAL_SUCCESS';
export const ARCHIVE_TUTORIAL_FAILURE = 'ARCHIVE_TUTORIAL_FAILURE';

export const VALIDATE_TUTORIAL_REQUEST = 'VALIDATE_TUTORIAL_REQUEST';
export const VALIDATE_TUTORIAL_SUCCESS = 'VALIDATE_TUTORIAL_SUCCESS';
export const VALIDATE_TUTORIAL_FAILURE = 'VALIDATE_TUTORIAL_FAILURE';
